#!/usr/bin/env python3
# gen_slot_configs.py — extract the ACTIVE non-UPJUMP slot roster (the 200DMA-muzzled
# sleeve) from src/main.cpp VERBATIM into slot_configs.inc for the replay harness.
# No hand-copied params: the Config initializers are lifted character-for-character
# from the production wiring, so the replay runs the exact deployed settings.
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
src = open(os.path.join(ROOT, "src", "main.cpp")).read()

# 1. active g_slots.push_back lines (not commented out)
active = []  # (tag, symbol, engine_var)
for ln in src.splitlines():
    s = ln.strip()
    if s.startswith("g_slots.push_back"):
        m = re.search(r'&(\w+),\s*"(\w+)",\s*\d+,\s*"([\w-]+)"', s)
        if m:
            active.append((m.group(3), m.group(2), m.group(1)))

non_upjump = [(t, s, v) for (t, s, v) in active if "UPJUMP" not in t]
sys.stderr.write(f"{len(active)} active slots, {len(non_upjump)} non-UPJUMP (muzzled sleeve)\n")

# 2. extract each engine's Config block verbatim
out = ["// AUTO-GENERATED by gen_slot_configs.py — DO NOT EDIT.",
       "// Verbatim EdgeEngine::Config initializers for the ACTIVE non-UPJUMP slot",
       "// roster lifted from src/main.cpp (the 200DMA-muzzled sleeve).", ""]
table = []
seen = set()
for tag, sym, var in non_upjump:
    # the engine's ctor names its actual cfg var (usually <var>_cfg, but e.g.
    # bnb_tsmom_d1 uses bnb_d1_cfg)
    mc = re.search(r'chimera::EdgeEngine\s+' + re.escape(var) + r'\s*\(\s*(\w+)\s*\)', src)
    if not mc:
        sys.stderr.write(f"MISSING ctor for {var} ({tag})\n"); sys.exit(1)
    cfgvar = mc.group(1)
    m = re.search(r'chimera::EdgeEngine::Config\s+' + re.escape(cfgvar) + r'\s*\{', src)
    if not m:
        sys.stderr.write(f"MISSING config {cfgvar} for {var} ({tag})\n"); sys.exit(1)
    i = m.end()  # after '{'
    depth = 1
    while depth > 0:
        if src[i] == '{': depth += 1
        elif src[i] == '}': depth -= 1
        i += 1
    # include trailing ';'
    j = src.find(';', i) + 1
    block = src[m.start():j]
    if cfgvar in seen:
        block = f"// (config {cfgvar} already emitted above)"
    else:
        seen.add(cfgvar)
        out.append(block)
        out.append("")
    table.append((tag, sym, cfgvar))

out.append("struct SlotDef { const char* tag; const char* symbol; chimera::EdgeEngine::Config* cfg; };")
out.append("static std::vector<SlotDef> make_slot_defs() {")
out.append("    return {")
for tag, sym, var in table:
    out.append(f'        {{"{tag}", "{sym}", &{var}}},')
out.append("    };")
out.append("}")

dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "slot_configs.inc")
open(dst, "w").write("\n".join(out) + "\n")
print(f"wrote {dst}: {len(table)} slot configs")
for t in table: print(" ", t[0])
