// ============================================================================
// veto_missed_bt.cpp — S-2026-07-12 missed-trades audit for the S54 200DMA
// macro veto (removed in 9f165c6, S-2026-07-11 BOUNCE RCA).
//
// QUESTION: what would the ACTIVE non-UPJUMP slot roster (24 TSMOM/ICHI
// engines, the "intermediate sleeve") have traded during the muzzled window
//   2026-05-31 03:00 UTC (S54j veto deploy, BTC already < 200d-MA)
//     -> 2026-07-11 11:00 UTC (9f165c6 fix deploy)
// had the veto not existed? During that entire window g_macro_bull was BEAR
// (journal: every [MACRO] line 74k spot vs 74-79k MA), so the veto blocked
// EVERY non-UPJUMP slot entry: the live baseline is exactly ZERO trades.
// The veto-off replay therefore IS the missed-trade delta.
//
// FAITHFULNESS:
//  * Runs the REAL production EdgeEngine.hpp (no reimplementation) with the
//    24 slot configs lifted VERBATIM from src/main.cpp (slot_configs.inc,
//    auto-generated by gen_slot_configs.py).
//  * Feed: Binance 1h klines as o,l,h,c ticks (adverse-low BEFORE favorable-
//    high — the S-2026-06-14 honest-fill convention from backtest_harness.cpp).
//    Engines aggregate to their native tf internally, exactly like live.
//  * Retained (non-veto) risk gates are modeled, since post-fix live still
//    applies them (this keeps the counterfactual honest, not a fantasy):
//      - per-symbol concurrency cap (1) + per-cluster cap (5), incl. occupancy
//        by the REAL live UPJUMP shadow positions (recovered closes)
//      - cluster 24h loss circuit-breaker (-150bp rolling)
//      - S54 chop-halt REGIME gate (BULL_TREND(3) required for trend kinds,
//        which all 24 are): global BTC regime + per-symbol regime, replicated
//        from main.cpp S34-r7/r8 logic. The 10-minute "short rally" return is
//        proxied from Binance 5m closes (live samples spot every 5s over a
//        120-sample = 10-min ring; 5m closes are the best offline proxy).
//        BTC D1/H4 trend + vol default BULLISH/1.0 live because no BTC TSMOM
//        D1/H4 slot is active — replicated. SOL/NEAR/SUI H4 trend and BNB D1
//        trend/vol are read from the replayed engines themselves, as live does.
//  * Costs: each engine's own round_trip_bp (20-22bp) via production net_bp.
//  * Convention: $10k notional per trade, 1bp = $1 (matches chimera_inbound).
//
// Modes:
//   ./veto_missed_bt              REGIME-GATED counterfactual (the honest one:
//                                 veto OFF, every other production gate ON)
//   ./veto_missed_bt --noregime   upper bound: regime chop-halt also OFF
//                                 (only concurrency + cluster-loss caps ON)
//
// Output: missed_trades_<mode>.csv + summary tables (full window + the
// Jul 8-11 bounce sub-window) to stdout.
//
// SHADOW throughout: live was shadow; "missed" = missed shadow/paper PnL.
// ============================================================================
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <functional>

#include "core/EdgeEngine.hpp"

#include "slot_configs.inc"

// ── window constants (UTC ms) ───────────────────────────────────────────────
static constexpr int64_t FEED_START_MS   = 1772323200000LL; // 2026-03-01 00:00 (warmup)
static constexpr int64_t WINDOW_START_MS = 1780196400000LL; // 2026-05-31 03:00 (veto live)
static constexpr int64_t WINDOW_END_MS   = 1783767600000LL; // 2026-07-11 11:00 (fix deploy)
static constexpr int64_t BOUNCE_START_MS = 1783641600000LL; // 2026-07-08 00:00
static constexpr int64_t HOUR_MS         = 3600000LL;

// ── production gate constants (src/main.cpp) ───────────────────────────────
static constexpr int    MAX_PER_SYMBOL      = 1;      // CLUSTER_MAX_PER_SYMBOL
static constexpr int    MAX_PER_CLUSTER     = 5;      // CLUSTER_MAX_PER_CLUSTER
static constexpr double CLUSTER_DAILY_CAP_BP = -150.0;

enum Cluster { CL_MAJORS=0, CL_L1, CL_DEFI, CL_MEME, CL_OTHER, CL_COUNT };
static int sym_cluster(const std::string& s) {
    // subset of main.cpp SYMBOL_CLUSTER relevant to this replay + UPJUMP overlay
    if (s=="btcusdt"||s=="ethusdt"||s=="bnbusdt") return CL_MAJORS;
    if (s=="solusdt"||s=="avaxusdt"||s=="suiusdt"||s=="aptusdt"||s=="nearusdt"||
        s=="tiausdt"||s=="seiusdt"||s=="adausdt"||s=="trxusdt") return CL_L1;
    if (s=="linkusdt"||s=="fetusdt"||s=="injusdt") return CL_DEFI;
    if (s=="dogeusdt") return CL_MEME;
    return CL_OTHER; // xrpusdt, opusdt, ...
}

// ── data ────────────────────────────────────────────────────────────────────
struct Bar { int64_t ts; double o,h,l,c; };

static bool load_csv(const std::string& path, std::vector<Bar>& out) {
    std::ifstream f(path);
    if (!f) return false;
    std::string line; std::getline(f, line); // header
    while (std::getline(f, line)) {
        Bar b{};
        if (sscanf(line.c_str(), "%lld,%lf,%lf,%lf,%lf",
                   (long long*)&b.ts, &b.o, &b.h, &b.l, &b.c) == 5)
            out.push_back(b);
    }
    return !out.empty();
}

// ── live UPJUMP shadow occupancy (recovered from journal / chimera_inbound.csv
//    + open_positions.json on josgp1) — these positions were REAL live shadow
//    exposure and consume per-symbol / per-cluster concurrency slots. ────────
struct Occ { const char* symbol; int64_t start_s, end_s; };
static const Occ UPJUMP_OCC[] = {
    {"opusdt",   1783513296, 1783515600},
    {"nearusdt", 1783559385, 1783562400},
    {"opusdt",   1783559404, 1783562400},
    {"nearusdt", 1783573060, 1783695600},
    {"solusdt",  1783578458, 1783580400},
    {"adausdt",  1783578827, 1783580400},
    {"adausdt",  1783580528, 1783584000},
    {"ethusdt",  1783655342, 1783656000},
    {"dogeusdt", 1783730035, 1783744092},
    {"ethusdt",  1783730035, 1783744092},
    {"dogeusdt", 1783745760, 1783900800},  // reopened, still open at fix time
    {"ethusdt",  1783745759, 1783900800},  // reopened, still open at fix time
};

// ── trade log ───────────────────────────────────────────────────────────────
struct TradeRow {
    std::string tag, symbol, reason;
    int64_t entry_ts=0, exit_ts=0;
    double entry_px=0, exit_px=0, gross_bp=0, net_bp=0, mfe_bp=0;
};

int main(int argc, char** argv) {
    bool noregime = false;
    for (int i=1;i<argc;i++) if (!strcmp(argv[i],"--noregime")) noregime = true;

    std::string dir = "data/";

    auto defs = make_slot_defs();

    // symbols needed
    std::vector<std::string> syms;
    for (auto& d : defs) if (std::find(syms.begin(),syms.end(),d.symbol)==syms.end())
        syms.push_back(d.symbol);

    // load 1h + 5m data
    std::map<std::string, std::vector<Bar>> h1;
    std::map<std::string, std::unordered_map<int64_t,double>> m5close; // key: bar CLOSE ts ms
    auto upper = [](std::string s){ for (auto& c : s) c = toupper(c); return s; };
    std::vector<std::string> allsyms = syms; allsyms.push_back("btcusdt");
    for (auto& s : allsyms) {
        std::string S = upper(s.substr(0, s.size())); // btcusdt -> BTCUSDT
        std::vector<Bar> v;
        if (!load_csv(dir + S + "_1h.csv", v)) { fprintf(stderr,"MISSING %s 1h\n",S.c_str()); return 1; }
        h1[s] = std::move(v);
        std::vector<Bar> m;
        if (!load_csv(dir + S + "_5m.csv", m)) { fprintf(stderr,"MISSING %s 5m\n",S.c_str()); return 1; }
        auto& mm = m5close[s];
        for (auto& b : m) mm[b.ts + 300000] = b.c;
    }

    // 10-min short-rally return (%) ending at ts (5m close proxy of the live
    // 5s-sampled 120-slot ring). NAN if data missing.
    auto ret10 = [&](const std::string& s, int64_t ts)->double {
        auto& mm = m5close[s];
        auto it1 = mm.find(ts), it0 = mm.find(ts - 600000);
        if (it1==mm.end()||it0==mm.end()||it0->second<=0) return NAN;
        return (it1->second/it0->second - 1.0)*100.0;
    };

    // engines
    std::vector<chimera::EdgeEngine*> eng;
    std::vector<TradeRow> trades;
    std::vector<std::pair<int64_t,std::pair<int,double>>> cl_pnl; // (exit_ts, (cluster, net_bp))
    for (auto& d : defs) {
        auto* e = new chimera::EdgeEngine(*d.cfg);
        std::string tag = d.tag, symbol = d.symbol;
        int cl = sym_cluster(symbol);
        e->set_on_trade([&, tag, symbol, cl](const chimera::EdgeEngine::TradeRecord& r){
            TradeRow t;
            t.tag=tag; t.symbol=symbol; t.reason=r.reason;
            t.entry_ts=r.entry_ts_ms; t.exit_ts=r.exit_ts_ms;
            t.entry_px=r.entry_px; t.exit_px=r.exit_px;
            t.gross_bp=r.gross_bp; t.net_bp=r.total_net_bp!=0.0?r.total_net_bp:r.net_bp;
            t.mfe_bp=r.mfe_bp;
            trades.push_back(t);
            cl_pnl.push_back({r.exit_ts_ms,{cl,t.net_bp}});
        });
        eng.push_back(e);
    }

    // per-symbol h1 cursor for d1 trend feed
    std::map<std::string,size_t> cur; for (auto& s : allsyms) cur[s]=0;

    // hour loop
    for (int64_t T = FEED_START_MS; T <= WINDOW_END_MS; T += HOUR_MS) {
        bool in_window = (T >= WINDOW_START_MS);

        // global BTC regime (S34-r7 with production defaults: no active BTC
        // TSMOM D1/H4 slot -> d1/h4 bullish=true, vol_ratio=1.0; so regime =
        // BULL_CHOP(2) iff 10-min rally > +0.2%, else BULL_TREND(3))
        double btc_r10 = ret10("btcusdt", T);
        int g_regime = (!std::isnan(btc_r10) && btc_r10 > 0.2) ? 2 : 3;

        // current concurrency occupancy: replayed engines + live UPJUMP shadow
        int open_sym_cnt[64] = {0}; // index into syms
        int open_cl_cnt[CL_COUNT] = {0};
        auto sym_idx = [&](const std::string& s)->int {
            for (size_t i=0;i<syms.size();++i) if (syms[i]==s) return (int)i;
            return -1;
        };
        for (size_t i=0;i<eng.size();++i)
            if (eng[i]->in_position()) {
                open_sym_cnt[sym_idx(defs[i].symbol)]++;
                open_cl_cnt[sym_cluster(defs[i].symbol)]++;
            }
        int64_t T_s = T/1000;
        for (auto& oc : UPJUMP_OCC)
            if (T_s >= oc.start_s && T_s < oc.end_s) {
                int si = sym_idx(oc.symbol);
                if (si >= 0) open_sym_cnt[si]++;
                open_cl_cnt[sym_cluster(oc.symbol)]++;
            }

        // cluster 24h rolling loss
        double cl_roll[CL_COUNT] = {0};
        for (auto& p : cl_pnl)
            if (p.first > T-86400000LL && p.first <= T) cl_roll[p.second.first] += p.second.second;

        for (size_t i=0;i<eng.size();++i) {
            auto* e = eng[i];
            const std::string& s = defs[i].symbol;
            auto& bars = h1[s];
            size_t& ci = cur[s + "/" + defs[i].tag];  // per-slot cursor
            // advance to the bar for this hour
            while (ci < bars.size() && bars[ci].ts < T) ++ci;
            if (ci >= bars.size() || bars[ci].ts != T) continue;  // no bar this hour

            // D1 trend feed (backtest_harness convention: 10-day lookback on 1h)
            if (ci >= 240)
                e->set_d1_bullish(bars[ci].c > bars[ci-240].c);

            // gates
            if (!in_window) {
                e->set_portfolio_gate(false);
                e->set_cluster_gate(true);
            } else {
                e->set_portfolio_gate(true);
                bool was_in = e->in_position();
                bool ok = true;
                if (!was_in) {
                    int si = sym_idx(s), cl = sym_cluster(s);
                    bool concurrency_ok  = (open_sym_cnt[si] < MAX_PER_SYMBOL) &&
                                           (open_cl_cnt[cl]  < MAX_PER_CLUSTER);
                    bool cluster_loss_ok = (cl_roll[cl] > CLUSTER_DAILY_CAP_BP);
                    bool regime_ok = true;
                    if (!noregime) {
                        // per-symbol regime (S34-r8/S35, production defaults for
                        // symbols with no active D1/H4 TSMOM slot)
                        bool d1b=true, h4b=true; double vr=1.0;
                        for (size_t j=0;j<eng.size();++j) {
                            if (defs[j].symbol != s) continue;
                            std::string jt = defs[j].tag;
                            if (jt.find("-TSMOM-")==std::string::npos) continue;
                            if (defs[j].cfg->tf_secs==86400) { d1b=eng[j]->trend_bullish(); vr=eng[j]->vol_ratio_public(); }
                            else if (defs[j].cfg->tf_secs==14400) h4b=eng[j]->trend_bullish();
                        }
                        double r10 = ret10(s, T);
                        bool rally = (!std::isnan(r10) && r10 > 0.2);
                        double rp  = std::isnan(r10) ? 0.0 : r10;
                        int sym_reg;
                        if (vr > 2.0) sym_reg = 0;
                        else if (!d1b && !h4b && !rally && rp < -0.5) sym_reg = 1;
                        else if (!d1b || !h4b || vr < 0.7 || vr > 1.3 || rally || rp <= 0.0) sym_reg = 2;
                        else sym_reg = 3;
                        // all 24 slots are trend kinds (TSMOM/ICHIMOKU): need BULL_TREND(3)
                        regime_ok = (g_regime >= 3) && (sym_reg >= 3);
                    }
                    ok = concurrency_ok && cluster_loss_ok && regime_ok;
                }
                e->set_cluster_gate(ok);
            }

            // honest fill: open, adverse low FIRST, favorable high, close
            bool was_in_pre = e->in_position();
            const Bar& b = bars[ci];
            e->on_tick(b.o, T);
            e->on_tick(b.l, T + 900000);
            e->on_tick(b.h, T + 1800000);
            e->on_tick(b.c, T + 2700000);

            // within-hour occupancy reconcile (live recomputes per tick): a new
            // entry must block later same-symbol/cluster engines THIS hour; an
            // exit frees the slot.
            bool now_in = e->in_position();
            if (now_in != was_in_pre) {
                int si = sym_idx(s), cl = sym_cluster(s);
                int d = now_in ? +1 : -1;
                open_sym_cnt[si] += d;
                open_cl_cnt[cl]  += d;
                if (open_sym_cnt[si] < 0) open_sym_cnt[si] = 0;
                if (open_cl_cnt[cl]  < 0) open_cl_cnt[cl]  = 0;
            }
        }
    }

    // mark-to-market any still-open position at window end
    std::vector<TradeRow> open_mtm;
    for (size_t i=0;i<eng.size();++i) {
        if (!eng[i]->in_position()) continue;
        // force a close via a final far-future tick? NO — report MTM instead.
        auto& bars = h1[defs[i].symbol];
        double last = bars.empty()?0.0:bars.back().c;
        TradeRow t; t.tag=defs[i].tag; t.symbol=defs[i].symbol; t.reason="OPEN@FIX";
        t.exit_ts=WINDOW_END_MS; t.exit_px=last;
        t.entry_px = eng[i]->entry_px();
        if (t.entry_px>0 && last>0) {
            t.gross_bp=(last/t.entry_px-1.0)*1e4;
            t.net_bp=t.gross_bp-defs[i].cfg->round_trip_bp;
        }
        open_mtm.push_back(t);
    }

    // filter to window trades (entry inside window)
    std::vector<TradeRow> wt;
    for (auto& t : trades)
        if (t.entry_ts >= WINDOW_START_MS && t.entry_ts <= WINDOW_END_MS) wt.push_back(t);

    // CSV
    std::string csvname = noregime ? "missed_trades_noregime.csv" : "missed_trades_gated.csv";
    FILE* f = fopen(csvname.c_str(), "w");
    fprintf(f, "tag,symbol,entry_ts,exit_ts,entry_px,exit_px,reason,gross_bp,net_bp,mfe_bp,in_bounce\n");
    auto emit=[&](const TradeRow& t){
        fprintf(f, "%s,%s,%lld,%lld,%.8f,%.8f,%s,%.2f,%.2f,%.2f,%d\n",
            t.tag.c_str(), t.symbol.c_str(), (long long)t.entry_ts, (long long)t.exit_ts,
            t.entry_px, t.exit_px, t.reason.c_str(), t.gross_bp, t.net_bp, t.mfe_bp,
            t.entry_ts >= BOUNCE_START_MS ? 1:0);
    };
    for (auto& t : wt) emit(t);
    for (auto& t : open_mtm) emit(t);
    fclose(f);

    // summary
    auto summarize=[&](const char* name, std::function<bool(const TradeRow&)> pred){
        int n=0,w=0; double net=0, gross=0, win_bp=0, lose_bp=0;
        for (auto& t : wt) if (pred(t)) {
            n++; net+=t.net_bp; gross+=t.gross_bp;
            if (t.net_bp>0){w++; win_bp+=t.net_bp;} else lose_bp+=t.net_bp;
        }
        printf("%-28s trades=%3d wins=%3d (%.0f%%)  gross=%+9.1fbp  net=%+9.1fbp"
               "  missed_winners=%+9.1fbp  avoided_losers=%+9.1fbp\n",
               name, n, w, n?100.0*w/n:0.0, gross, net, win_bp, lose_bp);
    };
    printf("\n=== %s counterfactual, window 2026-05-31 03:00 -> 2026-07-11 11:00 UTC ===\n",
           noregime?"NOREGIME (upper bound)":"REGIME-GATED (honest)");
    printf("($10k notional/trade, 1bp = $1; net includes each engine's round_trip_bp cost)\n\n");
    summarize("FULL WINDOW — all",        [](const TradeRow&){return true;});
    summarize("  TSMOM slots",            [](const TradeRow& t){return t.tag.find("ICHI")==std::string::npos;});
    summarize("  ICHI slots",             [](const TradeRow& t){return t.tag.find("ICHI")!=std::string::npos;});
    summarize("BOUNCE Jul8->fix — all",   [](const TradeRow& t){return t.entry_ts>=BOUNCE_START_MS;});
    printf("\nOpen at fix time (MTM, not in totals above):\n");
    for (auto& t : open_mtm)
        printf("  %-18s entry=%.6f last=%.6f  net=%+.1fbp\n",
               t.tag.c_str(), t.entry_px, t.exit_px, t.net_bp);

    // per-engine table
    printf("\nPer-engine (full window):\n");
    for (auto& d : defs) {
        int n=0,w=0; double net=0;
        for (auto& t : wt) if (t.tag==d.tag){n++;net+=t.net_bp;if(t.net_bp>0)w++;}
        if (n) printf("  %-18s trades=%2d wins=%2d net=%+8.1fbp\n", d.tag, n, w, net);
    }
    printf("\ntrade detail -> %s\n", csvname.c_str());
    return 0;
}
