# GenVersion.cmake — runs on every make via add_custom_target(gen_version ALL)
# Writes include/version_generated.hpp with the current git short hash.
# Using a cmake -P script avoids all shell quoting/escaping issues.

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT
)

if(NOT GIT_RESULT EQUAL 0 OR NOT GIT_HASH)
    set(GIT_HASH "unknown")
endif()

set(HEADER_CONTENT "#pragma once\n// Auto-generated by cmake/GenVersion.cmake — do not edit.\n#define BUILD_VERSION \"${GIT_HASH}\"\n")

set(OUTPUT_FILE "${CMAKE_SOURCE_DIR}/include/version_generated.hpp")

# Only write if content changed — avoids unnecessary recompilation
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" EXISTING_CONTENT)
else()
    set(EXISTING_CONTENT "")
endif()

if(NOT EXISTING_CONTENT STREQUAL HEADER_CONTENT)
    file(WRITE "${OUTPUT_FILE}" "${HEADER_CONTENT}")
    message(STATUS "GenVersion: wrote ${GIT_HASH} -> include/version_generated.hpp")
else()
    message(STATUS "GenVersion: hash unchanged (${GIT_HASH})")
endif()
